# Generated by Django 5.1.1 on 2025-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('brokername', models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART')], default=None, max_length=100, null=True)),
                ('accountnumber', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('apikey', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('secretkey', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('vendorcode', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('imei', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('AuthToken', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('value', models.BooleanField(blank=True, default=False, null=True)),
                ('websocket', models.BooleanField(blank=True, default=False, null=True)),
                ('indexscalp', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderobject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyorderid', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('tradingsymbol', models.TextField(blank=True, default='', null=True)),
                ('symboltoken', models.TextField(blank=True, default='', null=True)),
                ('order_type', models.TextField(blank=True, default=None, null=True)),
                ('transactiontype', models.TextField(blank=True, default=None, null=True)),
                ('product_type', models.TextField(blank=True, default=None, null=True)),
                ('avg_price', models.FloatField(blank=True, default=None, null=True)),
                ('indexprice', models.TextField(blank=True, default=None, null=True)),
                ('quantity', models.TextField(blank=True, default=None, null=True)),
                ('exchange', models.TextField(blank=True, default=None, null=True)),
                ('broker', models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART')], default=None, max_length=100, null=True)),
                ('sellorderid', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('side', models.TextField(blank=True, default=None, null=True)),
                ('orderstatus', models.TextField(blank=True, default=None, null=True)),
                ('Blockid', models.IntegerField(blank=True, default=None, null=True)),
                ('ltp', models.FloatField(blank=True, default=None, null=True)),
                ('lotsize', models.IntegerField(blank=True, default=None, null=True)),
                ('sellorderstatus', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('CANCELED', 'CANCELED'), ('PENDING', 'PENDING'), ('MODIFIED', 'MODIFIED'), ('COMPLETE', 'COMPLETE')], default=None, max_length=20, null=True)),
                ('buyorderstatus', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('CANCELED', 'CANCELED'), ('PENDING', 'PENDING'), ('MODIFIED', 'MODIFIED'), ('COMPLETE', 'COMPLETE')], default=None, max_length=20, null=True)),
                ('paper', models.BooleanField(blank=True, default=False, null=True)),
                ('pnl', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('sellprice', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
