# Generated by Django 5.1.1 on 2025-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='globalsymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orderpunchsymbol', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('tradingsymbol', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('symboltoken', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('exchange', models.CharField(blank=True, choices=[('NSE', 'NSE'), ('NFO', 'NFO'), ('BSE', 'BSE'), ('BFO', 'BFO')], default=None, max_length=200, null=True)),
            ],
        ),
    ]
