# Generated by Django 5.1.1 on 2025-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0002_globalsymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART')], default=None, max_length=200, null=True)),
                ('orderpunchsymbol', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('tradingsymbol', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('symnol', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('symboltoken', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('exchange', models.CharField(blank=True, choices=[('NSE', 'NSE'), ('NFO', 'NFO'), ('BSE', 'BSE'), ('BFO', 'BFO')], default=None, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='broker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='indexscalp',
        ),
        migrations.AddField(
            model_name='broker',
            name='brokerid',
            field=models.IntegerField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
