# Generated by Django 5.1.1 on 2025-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0003_watchlist_remove_broker_id_remove_broker_indexscalp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='brokerid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
