# Generated by Django 5.1.1 on 2025-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0004_alter_broker_brokerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='brokerid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
