# Generated by Django 5.1.1 on 2025-05-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0005_alter_broker_brokerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderobject',
            old_name='buyorderid',
            new_name='orderid',
        ),
        migrations.RemoveField(
            model_name='orderobject',
            name='Blockid',
        ),
    ]
