# Generated by Django 5.1.1 on 2025-05-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0006_rename_buyorderid_orderobject_orderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderobject',
            name='accountno',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
