# Generated by Django 5.1.1 on 2025-05-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0007_orderobject_accountno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='value',
            new_name='valid',
        ),
    ]
