# Generated by Django 5.1.1 on 2025-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0008_rename_value_broker_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='subscribe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
