# Generated by Django 5.1.1 on 2025-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0009_watchlist_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='newevent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
