# Generated by Django 5.1.1 on 2025-05-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0010_watchlist_newevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='lotsize',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
