# Generated by Django 5.1.1 on 2025-05-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0011_watchlist_lotsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='ltp',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
