# Generated by Django 5.1.1 on 2025-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0012_watchlist_ltp'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='OI',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='volume',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
