# Generated by Django 5.1.1 on 2025-05-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0014_watchlist_instrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderobject',
            old_name='order_type',
            new_name='ordertype',
        ),
        migrations.AddField(
            model_name='broker',
            name='nickname',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderobject',
            name='discloseqty',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderobject',
            name='instrument',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART')], default=None, max_length=100, null=True),
        ),
    ]
