# Generated by Django 5.1.1 on 2025-05-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0016_broker_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allpositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tradingsymbol', models.TextField(blank=True, default='', null=True)),
                ('symboltoken', models.TextField(blank=True, default='', null=True)),
                ('ordertype', models.TextField(blank=True, default=None, null=True)),
                ('transactiontype', models.TextField(blank=True, default=None, null=True)),
                ('producttype', models.TextField(blank=True, default=None, null=True)),
                ('buyavgprice', models.FloatField(blank=True, default=None, null=True)),
                ('indexprice', models.TextField(blank=True, default=None, null=True)),
                ('netqty', models.TextField(blank=True, default=None, null=True)),
                ('exchange', models.TextField(blank=True, default=None, null=True)),
                ('broker', models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART')], default=None, max_length=100, null=True)),
                ('accountnumber', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ltp', models.FloatField(blank=True, default=None, null=True)),
                ('lotsize', models.IntegerField(blank=True, default=None, null=True)),
                ('sellorderstatus', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('CANCELED', 'CANCELED'), ('PENDING', 'PENDING'), ('MODIFIED', 'MODIFIED'), ('COMPLETE', 'COMPLETE')], default=None, max_length=20, null=True)),
                ('buyorderstatus', models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('CANCELED', 'CANCELED'), ('PENDING', 'PENDING'), ('MODIFIED', 'MODIFIED'), ('COMPLETE', 'COMPLETE')], default=None, max_length=20, null=True)),
                ('pnl', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('realised', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('unrealised', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('sellavgprice', models.FloatField(blank=True, default=0, null=True)),
                ('instrument', models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART')], default=None, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='orderobject',
            old_name='accountno',
            new_name='accountnumber',
        ),
        migrations.AddField(
            model_name='orderobject',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
