# Generated by Django 5.1.1 on 2025-05-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0017_allpositions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpositions',
            name='instrument',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='pnl',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='realised',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='sellavgprice',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='unrealised',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
