# Generated by Django 5.1.1 on 2025-05-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0018_alter_allpositions_instrument_alter_allpositions_pnl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='allholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tradingsymbol', models.TextField(blank=True, default='', null=True)),
                ('symboltoken', models.TextField(blank=True, default='', null=True)),
                ('product', models.TextField(blank=True, default=None, null=True)),
                ('averageprice', models.FloatField(blank=True, default=None, null=True)),
                ('quantity', models.TextField(blank=True, default=None, null=True)),
                ('exchange', models.TextField(blank=True, default=None, null=True)),
                ('broker', models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART')], default=None, max_length=100, null=True)),
                ('accountnumber', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ltp', models.FloatField(blank=True, default=None, null=True)),
                ('lotsize', models.IntegerField(blank=True, default=None, null=True)),
                ('profitandloss', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('instrument', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pnlpercentage', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('totalprofitandloss', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('totalpnlpercentage', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='broker',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
