# Generated by Django 5.1.1 on 2025-05-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0019_allholding_alter_broker_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobject',
            name='instrument',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
