# Generated by Django 5.1.1 on 2025-05-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0020_alter_orderobject_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobject',
            name='buyorderstatus',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('CANCELED', 'CANCELED'), ('PENDING', 'PENDING'), ('MODIFIED', 'MODIFIED'), ('COMPLETE', 'COMPLETE')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='discloseqty',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='orderstatus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='sellorderid',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='sellorderstatus',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('CANCELED', 'CANCELED'), ('PENDING', 'PENDING'), ('MODIFIED', 'MODIFIED'), ('COMPLETE', 'COMPLETE')], default='', max_length=20, null=True),
        ),
    ]
