# Generated by Django 5.1.1 on 2025-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0021_alter_orderobject_buyorderstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
