# Generated by Django 5.1.1 on 2025-05-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0022_broker_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='AuthToken',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
