# Generated by Django 5.1.1 on 2025-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0023_alter_broker_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderobject',
            name='lastmodifiedtime',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allholding',
            name='broker',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='broker',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='apikey',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='brokername',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='imei',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='broker',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='broker',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE')], default=None, max_length=200, null=True),
        ),
    ]
