# Generated by Django 5.1.1 on 2025-06-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0024_orderobject_lastmodifiedtime_alter_allholding_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpositions',
            name='lastmodifiedtime',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
