# Generated by Django 5.1.1 on 2025-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0025_allpositions_lastmodifiedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allholding',
            name='broker',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE'), ('HDFC', 'HDFC')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='broker',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE'), ('HDFC', 'HDFC')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='brokername',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE'), ('HDFC', 'HDFC')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='broker',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE'), ('HDFC', 'HDFC')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='broker',
            field=models.CharField(blank=True, choices=[('ANGEL', 'ANGEL'), ('SHOONYA', 'SHOONYA'), ('DHAN', 'DHAN'), ('FYERS', 'FYERS'), ('MOTILAL', 'MOTILAL'), ('ANANDRATHI', 'ANANDRATHI'), ('GROWW', 'GROWW'), ('ZERODHA', 'ZERODHA'), ('SAMCO', 'SAMCO'), ('FLATTRADE', 'FLATTRADE'), ('BIGUL', 'BIGUL'), ('STOXKART', 'STOXKART'), ('UPSTOX', 'UPSTOX'), ('ALICEBLUE', 'ALICEBLUE'), ('HDFC', 'HDFC')], default=None, max_length=200, null=True),
        ),
    ]
